### ISSUE TITLE
 CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.       -- Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by chuwenhao123** [pyswmm/swmm-python#124]
Greetings,
 I am currently endeavoring to submit a pull request for the swmmio library. However, I encountered an [error in line 286](https://github.com/pyswmm/swmmio/actions/runs/6308831232/job/17127919217#step:4:336) on macOS, which has resulted in the failure to build wheels for swmm-toolkit (version 0.10.0). Unfortunately, the nature of the error is not clear to me. Could you kindly provide some suggestions or guidance on how to address this issue?
 Thank you for your assistance.

Moved some info from GH Issue Subject to here:

CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.       -- Configuring incomplete, errors occurred!

**Comment by chuwenhao123** [comment]
It appears to be an issue related to swmm-toolkit (pyproject.toml), but I am not certain yet. 
![image](https://github.com/pyswmm/swmm-python/assets/51478550/ad4bb24f-b88d-4941-90e5-87bb36fb3e2e)

**Comment by chuwenhao123** [comment]
![image](https://github.com/pyswmm/swmm-python/assets/51478550/8b1ffbe2-fba3-451f-b64b-7e196918a01d)

**Comment by chuwenhao123** [comment]
@bemcdonnell, It appears that we are encountering an issue related to "CMAKE_MAKE_PROGRAM." At this moment, I'm uncertain whether this issue is associated with [scikit-build](https://github.com/scikit-build/scikit-build/issues/755) or if there might be a problem with the definition of the [path](https://github.com/facebookarchive/xcbuild/issues/108).
![image](https://github.com/pyswmm/swmm-python/assets/51478550/f2cd8912-ec8d-4642-aa56-9ab8abf6db30)
![image](https://github.com/pyswmm/swmm-python/assets/51478550/2d9d4f83-149b-49b7-a427-e4f3ead23f8b)

**Comment by bemcdonnell** [comment]
@chuwenhao123 Our CI services in SWMMIO are configured to cancel all builds when one fails.  We've made some recent changes to the mac build workflow here in swmm-python and I'm thinking that's the issue. I am rerunning them by hand to see which ones I can get to pass.  So far we are seeing green lights on Windows/Ubuntu. 

@karosc, Have a peek at this: https://github.com/pyswmm/swmmio/pull/205 

with swmmio we can bump down the pyswmm version as an option and/or we can fix the build workflow.  The former lets the SWMMIO PR pass, the latter still needs to be done regardless.  (@karosc @aerispaha, thoughts?)

**Comment by bemcdonnell** [comment]
@karosc Python-3.10 mac builds (how i am feeling 🤪)

**Comment by karosc** [comment]
@bemcdonnell and @chuwenhao123 ,  we will need to add ninja to the pyproject.toml build requirements for this to build on python 3.7 since we don't build wheels for that version anymore.

I'd also recommend that swmmio deprecate python 3.7 unit tests since [3.7 has reached end of life](https://devguide.python.org/versions/).

I can add the ninja dependency later today and issues 0.15.3 release, but if you move things forward without removing the 3.7 tests should solve the unit test issues.
