### ISSUE TITLE
Prevent extend_enum if pollutant name already exists

### ISSUE THREAD

**Issue by stroutm** [pyswmm/swmm-python#130]
This happens if [OutputMetadata](https://github.com/pyswmm/swmm-python/blob/e2e25c33fbd6f7492f13d8251db6d691c7a98e10/swmm-toolkit/src/swmm/toolkit/output_metadata.py#L18C7-L18C21) is instantiated more than once.

If `symbolic_name` is already present, an error will be thrown.

**Comment by stroutm** [comment]
Opened [PR](https://github.com/pyswmm/swmm-python/pull/131)

**Comment by bemcdonnell** [comment]
Hey @stroutm!  Great to see you in the code.  And thanks for sharing your fix! Can you show a little but of the code you were using that threw the error?  I looked at the PR for a minute and it's making me think of something else related to this.

**Comment by stroutm** [comment]
I am trying to read from the SWMM out file more than once, in which `output_metadata.OutputMetadata(p_handle)` is called each time. Doing so results in the following traceback:
![traceback_pollut_metadata](https://github.com/pyswmm/swmm-python/assets/15223373/7923e155-de97-4b10-8ccc-43290b8752ba)
